name: Environmentvariables

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run venkatesh.postman_collection.csv

      - name: Upload Newman Report
        uses: actions/upload-artifact@v2
        with:
          name: newman-report
          path: .github/workflows/blank.yml
